dependencies:
- name: kibana
  version: "6.1.3"
  repository: https://raw.githubusercontent.com/nwsheppard/helm-charts/master/charts/
  #repository: file://../kibana
- name: elasticsearch
  version: "6.1.3"
  repository: https://raw.githubusercontent.com/nwsheppard/helm-charts/master/charts/
  #repository: file://../elasticsearch
- name: fluent-bit
  version: "0.6.0"
  repository: https://kubernetes-charts.storage.googleapis.com/
